### ISSUE TITLE
Generate Debug information

### ISSUE THREAD

**Issue by Ginson** [danielpinto8zz6/c-cpp-compile-run#114]
**Is your feature request related to a problem? Please describe.**
User should be able to debug the code.

**Describe the solution you'd like**
An option to generate an exe in debug mode should be provided in settings. So the user can debug the exe by placing breakpoints.

**Describe alternatives you've considered**
Nil

**Additional context**
NA

**Comment by danielpinto8zz6** [comment]
Hi,
You can add debug flags to the compile args

**Comment by Ginson** [comment]
> Hi,
> You can add debug flags to the compile args

Hi @danielpinto8zz6 ,
Thanks for reply. Is there an option to do this in extension. If yes, can you share a screenshot of the option please.

**Comment by danielpinto8zz6** [comment]
![Captura de ecrã de 2020-04-11 03-04-51](https://user-images.githubusercontent.com/8846362/79032817-4113f700-7ba1-11ea-84cf-92768389198c.png)
Just add "-g" to C-Flags

**Comment by Ginson** [comment]
> ![Captura de ecrã de 2020-04-11 03-04-51](https://user-images.githubusercontent.com/8846362/79032817-4113f700-7ba1-11ea-84cf-92768389198c.png)
> Just add "-g" to C-flags

Thanks a lot @danielpinto8zz6 !!!

**Comment by danielpinto8zz6** [comment]
Added by default, along with support to debug
