### ISSUE TITLE
Please add a feature that allows program to run in a new window

### ISSUE THREAD

**Issue by GNAQ** [danielpinto8zz6/c-cpp-compile-run#12]
The executable file only runs in VSCode terminal, and this always makes me headache when I needed to input a lot of data.

**Comment by danielpinto8zz6** [comment]
so, are you asking for external terminal?

**Comment by GNAQ** [comment]
yeah

**Comment by Anti-Li** [comment]
@danielpinto8zz6 We can use "start" command, but I don't think it as a elegant way.

**Comment by danielpinto8zz6** [comment]
yeah, plus we need to handle the terminals in linux (there are plenty) and windows and mac, for now I won't focus in this
