### ISSUE TITLE
Run executable not work on Windows.

### ISSUE THREAD

**Issue by MapleCCC** [danielpinto8zz6/c-cpp-compile-run#124]
**Describe the bug**
Run executable not work in Windows. Error message is "file not found". It seems the problem is that the extension runs command like "filename.exe" instead of "./filename.exe".

**To Reproduce**
Just simply compile and run a naive Cpp file.

**Expected behavior**
File is successfully compiled, but fails running.

**Screenshots**
![image](https://user-images.githubusercontent.com/25131775/72324882-e294c500-36e6-11ea-9e8a-5534f2ca2883.png)

**Environment**
 - VSCode Version: [1.41.1]
 - OS Version: [Windows 10]

**Additional context**
I digged in the source and found that the problem seem to be located on [this line](https://github.com/danielpinto8zz6/c-cpp-compile-run/blob/cd93e28d34f6f6bf3d8f440eb03a39a20465909e/src/run.ts#L41):

```typescript
        await terminal.run(`"${this.file.executable}" ${this.arguments}`, { name: 'C/C++ Compile Run', cwd: this.file.directory });
```

**Comment by martygurl** [comment]
run ./main.exe instead
