### ISSUE TITLE
Let the default flag with latest c++ standard

### ISSUE THREAD

**Issue by Naishiro** [danielpinto8zz6/c-cpp-compile-run#13]
Please make default command (cmd+r) with flag -std=c++17 or let user change the default flat easily.
every time want to compile&run c++17 is troubling.

**Comment by Anti-Li** [comment]
I think "let user change the default" compile args is better.

**Comment by danielpinto8zz6** [comment]
yes, that's better

**Comment by Anti-Li** [comment]
Let me achieve it.

**Comment by danielpinto8zz6** [comment]
Thanks :1st_place_medal:
