### ISSUE TITLE
How to change compiler options?

### ISSUE THREAD

**Issue by Anguei** [danielpinto8zz6/c-cpp-compile-run#14]
How to change compiler options in new version? ./out/extension.js has been changed so I couldn't find a way to edit compiler options such as-DLOCAL

**Comment by danielpinto8zz6** [comment]
You have now an option to compile with flags in the command pallet.
Plus it being added a freature that allow to set default flags, will be coming soon

**Comment by Anti-Li** [comment]
There is a option "Run with arguments" and another option "Compile with flags". But if I want to "Run with arguments" and "Compile with flags" at the same time, is there a way?

**Comment by danielpinto8zz6** [comment]
Well, no but it can be easly implemented as the functions are already there

**Comment by Anti-Li** [comment]
How to get a array type setting in the program?

**Comment by Anti-Li** [comment]
Similar to #13. Close it. @danielpinto8zz6
