### ISSUE TITLE
Only keep two command. One is run and compile directly, And the other is run and compile with args. If the user choose the second command, we will give him two input box. One is about compile args(the default value can be set), the other is about run args(the default value can be set).

### ISSUE THREAD

**Issue by Anti-Li** [danielpinto8zz6/c-cpp-compile-run#16]
_Originally posted by @Anti-Li in https://github.com/danielpinto8zz6/c-cpp-compile-run/issues/14#issuecomment-425767535_

**Comment by Anti-Li** [comment]
Now we have default args, and we should simplified run and compile combination logic.

**Comment by danielpinto8zz6** [comment]
yes, I am still trying to find how to make double input box, since I didn't find it in the api docs

**Comment by Anti-Li** [comment]
impossible.
Just see Microsoft/vscode#9936

**Comment by danielpinto8zz6** [comment]
It was 2 years ago, I don't know if it was already added

**Comment by Anti-Li** [comment]
Maybe not :joy:

**Comment by Anti-Li** [comment]
This Feature Request is in ![Backlog](https://github.com/Microsoft/vscode/milestone/8)
