### ISSUE TITLE
exit time of code

### ISSUE THREAD

**Issue by Navin009** [danielpinto8zz6/c-cpp-compile-run#167]
I try to practice coding for exams the time complexity of code is important i kindly request to add the 
exeited time at the end of the code exection this help me to improve coding skills and make more efficient logics 

![image](https://user-images.githubusercontent.com/62857427/77862266-f789ea80-7237-11ea-96fd-295419876295.png)

**Comment by danielpinto8zz6** [comment]
have you tried to add `-ftime-report` to c or cpp flags in settings?

**Comment by Navin009** [comment]
it shows the compile time of code not execution time. when i try to solve problem on hackerearth web it bound to code execution time for logics.

**Comment by danielpinto8zz6** [comment]
I'll take a look

**Comment by danielpinto8zz6** [comment]
Closing, won't do for now
