### ISSUE TITLE
Log from console :`rejected promise not handled within 1 second `

### ISSUE THREAD

**Issue by Anti-Li** [danielpinto8zz6/c-cpp-compile-run#17]
_Originally posted by @danielpinto8zz6 in https://github.com/danielpinto8zz6/c-cpp-compile-run/pull/15#issuecomment-425861635_

**Comment by Anti-Li** [comment]
wagenaartje/neataptic#85
https://stackoverflow.com/questions/50112269/rejected-promise-not-handled-within-1-second-vscode-extension-api

**Comment by danielpinto8zz6** [comment]
can you explain?

**Comment by Anti-Li** [comment]
Microsoft/vscode#60081

**Comment by Anti-Li** [comment]
Not cause by this extension. It is already fixed by Microsoft/vscode-cpptools#2632.
