### ISSUE TITLE
Directory change after each run using F6

### ISSUE THREAD

**Issue by ojhalakshya** [danielpinto8zz6/c-cpp-compile-run#172]
**Describe the bug**
Whenever I compile and run using F6, the current directory changes to the directory of the file I am trying to run.
For ex:
I am inside 

> Desktop/CPP

 which is my git repo, I write code inside 

> Desktop/CPP/Vectors/sort.cpp

and press F6. The code runs and the directory changes to Desktop/CPP/Vectors.
Because of this I am not able to `git add .` and `git commit -m "new commit"` because I am not inside the git repo folder instead inside its sub folder.

**To Reproduce**
1. Go to 'Desktop/CPP'
2. Click on 'Array/rough.cpp'
3. Press F6

**Expected behavior**
Previously even after running the directory was remaining the same so I was not concerned about maintaining the correct directory, but now I have to change it each time using `cd ../` commands which is a drawback and discourage me to use this feature of F6.

This is before using F6.
![Screenshot from 2020-04-06 00-39-21](https://user-images.githubusercontent.com/57477999/78507751-869a8380-779f-11ea-907f-c409bc17b1ba.png)

This is after using F6.

![imageedit_2_6405823336](https://user-images.githubusercontent.com/57477999/78507761-a29e2500-779f-11ea-8a4e-a7b7b6dc0b66.jpg)

**Environment**
 - VSCode Version: [1.43]
 - OS Version: [Pop_os ubuntu 19.04]

**Additional context**
This problem was not coming before sometime, starting coming recently.
Please help with the same.

**Comment by danielpinto8zz6** [comment]
Hi, that's the expected behavior, it creates a new terminal and goes into the file folder, if you delete the terminal created by the extension you still have your terminal in your folder.

**Comment by kartikdutt18** [comment]
I think this is solved. Should we close this.

**Comment by danielpinto8zz6** [comment]
yes
