### ISSUE TITLE
error

### ISSUE THREAD

**Issue by farjiwada** [danielpinto8zz6/c-cpp-compile-run#177]
Issue Type: <b>Bug</b>

PS C:\Users\SINGH PAVAN UMESH\Desktop\cpp> cd "c:\Users\SINGH PAVAN UMESH\Desktop\cpp\.vscode"
PS C:\Users\SINGH PAVAN UMESH\Desktop\cpp\.vscode> & ./"main.exe"
Program 'main.exe' failed to run: Access is deniedAt line:1 char:1
+ & ./"main.exe" 
+ ~~~~~~~~~~~~~~.
At line:1 char:1
+ & ./"main.exe"
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

Extension version: 1.0.8
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by danielpinto8zz6** [comment]
can you test with another console?

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/5026dba1e0cb9043844d800971af97ed60604373

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/5026dba1e0cb9043844d800971af97ed60604373
