### ISSUE TITLE
Could you please give me an example of the path,thank you .

### ISSUE THREAD

**Issue by rizaust** [danielpinto8zz6/c-cpp-compile-run#18]
![image](https://user-images.githubusercontent.com/34341804/46458829-a7b89780-c7e9-11e8-841b-0156d170e024.png)
It always recommend me this.

**Comment by rizaust** [comment]
this is what i had input

**Comment by danielpinto8zz6** [comment]
C:\\Program Files (x86)\\MinGW64\\bin\\gcc.EXE
Try that

**Comment by rizaust** [comment]
it doesn't work too

**Comment by danielpinto8zz6** [comment]
Remove the setting and add it to your windows variables PATH

**Comment by rizaust** [comment]
Thank you , let me try

**Comment by rizaust** [comment]
> C:\\Program Files (x86)\\MinGW64\\bin\\gcc.exe
> Try that

I've tried that but it doesn't work too

**Comment by rizaust** [comment]
Thank you for your patience

**Comment by danielpinto8zz6** [comment]
It worked?
