### ISSUE TITLE
gcc  saves output in wrong directory with modified tasks.json

### ISSUE THREAD

**Issue by leemke** [danielpinto8zz6/c-cpp-compile-run#184]
Issue Type: <b>Bug</b>

1. created a dummy "xxxx.h" file (simple function definition) in project directory.

2' added new folder to project named "Build"

3. Modified tasks.json args array from
     ... "-o", "${fileDirname}/$(fileBasenameNoExtension}"...
  to .. "-o","${fileDirname}/Build/${fileBasenameNoExtension}".....

4. Ran the command  normal command that I run for .cpp programs.

I expected to find the output in the Build directory of the workspace
directory where the .h file is located. The output was sent to the same
directory as the .h file. 

I have tested the modified '-o' arguement using linuxc gcc command line terminal
input. It places the output in the Build directory.

But not under VSCode.
I expect the same will be true when I run the hello_world.cpp program

Extension version: 1.0.8
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.19.98-08076-g24ab33fb8e14

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (2 x 1607)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|6.48GB (2.36GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by danielpinto8zz6** [comment]
This extension has nothing to do with tasks.json
