### ISSUE TITLE
Auto save file

### ISSUE THREAD

**Issue by TitanSnow** [danielpinto8zz6/c-cpp-compile-run#2]
How about adding the feature that automatically saving file before compilation?

**Comment by danielpinto8zz6** [comment]
Yes, I'll add it as a option

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/b27f4d5e65b9a5f8ae4ce9fc11ef00b75fdadcbb
