### ISSUE TITLE
When there is something in the terminal, the commands that are run will be superimposed directly.

### ISSUE THREAD

**Issue by Anti-Li** [danielpinto8zz6/c-cpp-compile-run#20]
I write "Hello world" in the terminal, and don't clear them. Then I run my cpp file, the command will be "Hello worlda.exe".
To solve it, please call a command to clear the terminal first.

**Comment by danielpinto8zz6** [comment]
the clear won't solve it

**Comment by Anti-Li** [comment]
BTW, can I clear the output of last run?

**Comment by danielpinto8zz6** [comment]
yeah, by recreating the ouput channel

**Comment by Anti-Li** [comment]
I mean the output of running program but not the result of compiling.

**Comment by Anti-Li** [comment]
Can I make it clear the terminal every time?

**Comment by danielpinto8zz6** [comment]
the output window can be deleted and created a new one

**Comment by Anti-Li** [comment]
Can I make extension work like that?

**Comment by danielpinto8zz6** [comment]
yes

**Comment by danielpinto8zz6** [comment]
for now, let's keep as it is
