### ISSUE TITLE
update v1.0.10 causing compiling error.

### ISSUE THREAD

**Issue by manujgrover71** [danielpinto8zz6/c-cpp-compile-run#203]
When the extension updates to v1.0.10, the new command 

**`cmd /c ${cmd}`**

isn't working anymore in my powershell.

**Screenshot**
![image](https://user-images.githubusercontent.com/56198659/82810291-b0bd1780-9eab-11ea-9548-7faec2960eef.png)

While the previous command for powershell:
**`& ${cmd}`**

is working fine.

After doing some changes, this is working fine.
**Screenshot**
![image](https://user-images.githubusercontent.com/56198659/82810495-4ce71e80-9eac-11ea-8f31-1041baed2080.png)

**Environment**
 - VSCode Version: 1.45.1
 - OS Version: Windows 10 Version 1909

**Comment by danielpinto8zz6** [comment]
try new version 1.0.11

**Comment by manujgrover71** [comment]
It's working fine now.
