### ISSUE TITLE
Alternative key binding to F6

### ISSUE THREAD

**Issue by sachingodishela** [danielpinto8zz6/c-cpp-compile-run#208]
Hi Daniel,
Since significant amount of users use laptop's keyboard, it is a bit difficult to find the Fn and F6 keys everytime. Hence I request to add an optional keyboard shortcut which is easier than F6//F7 keys    , for example, ctr + R or ctrl + (any letter in alphabet).

Thanks.
Btw, love this extension!

**Comment by danielpinto8zz6** [comment]
CTRL+R is already used by vscode, maybe CTRL+6 or something like that
