### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by User9029** [danielpinto8zz6/c-cpp-compile-run#209]
**Describe the bug**

Hello I just have a small problem that I do not know how to fix.
I have downloaded the requirements to use the Compile/Run extension on Windows, however, whenever I hit F6 or Cntrl + Shift + P then Compile and run with default ...etc. , nothing is happening for some reason. In other words, it is like the command is being totally ignored. I am pretty sure it is some Path issues that I am not able to fix. Maybe it is something else but can someone help me?

**Comment by danielpinto8zz6** [comment]
it doesn't show you any error?

**Comment by User9029** [comment]
It showed me "not recognized as an internal command ..." error once but now it simply isn't showing me anything.

**Comment by danielpinto8zz6** [comment]
it means you don't have gcc on your path

**Comment by DoidArthas** [comment]
I have the same issue, but my path is ok, and the compiler show no error on compilation. Trying by "Ctrl+shift+b" also compiles the code but dont execute.
