### ISSUE TITLE
How to setup for C++ 03/11/14/17 versions

### ISSUE THREAD

**Issue by giornaledisistema** [danielpinto8zz6/c-cpp-compile-run#217]
Hi Daniel,
I use this C++ code
```
#include<iostream>

int main() {
    if (__cplusplus == 201703L) std::cout << "C++17\n";
    else if (__cplusplus == 201402L) std::cout << "C++14\n";
    else if (__cplusplus == 201103L) std::cout << "C++11\n";
    else if (__cplusplus == 199711L) std::cout << "C++98\n";
    else std::cout << "pre-standard C++\n";
}
```
to determine which version of C++ use my g++ compiler on Ubuntu 18.04 with VSC and your extension when I use F6 key. The result it's "C++14" string.
I want to use C++ 11 version and I tried to setting this version in task.json file of VSC with "-std=c++11" argument inside task.json without effect:
```
"type": "shell",
"label": "C/C++: g++ build active file",
"command": "/usr/bin/g++",
"args": [
"-std=c++11",
"-g",
"${file}",
"-o",
"${fileDirname}/${fileBasenameNoExtension}"
]
```
Is it possible to change C++ version in some other way?
Thank you very much.

**Comment by giornaledisistema** [comment]
Ok, I found it. From menu

_File | Preferences | Settings | Compile Run configuration | Cpp-flags_

add option

`-std=c++11`

for C++ 11 version.
Tks.

**Comment by danielpinto8zz6** [comment]
Glad you find out :+1:
