### ISSUE TITLE
Problem setting compiler path

### ISSUE THREAD

**Issue by Ranner198** [danielpinto8zz6/c-cpp-compile-run#22]
I'm sure its just a silly issue I'm doing but here's what I got: 
![image](https://user-images.githubusercontent.com/28194149/46715207-adb4db00-cc24-11e8-8665-59994d9a8fd0.png)

![image](https://user-images.githubusercontent.com/28194149/46715222-bd342400-cc24-11e8-9476-7e0272052f66.png)

**Comment by danielpinto8zz6** [comment]
use gcc for cpp too, it will work

**Comment by Ranner198** [comment]
Thanks for the quick response, I'm out of town for the weekend but I'll give it a shot Monday!

**Comment by danielpinto8zz6** [comment]
fixed, you can use g++ also now
