### ISSUE TITLE
compilation Error

### ISSUE THREAD

**Issue by fayazmum** [danielpinto8zz6/c-cpp-compile-run#228]
**Describe the bug**
when i want to compile and run program cmd shows me something like that how to solve it

**To Reproduce**

**Expected behavior**

**Screenshots**
![Annotation 2020-08-21 082825](https://user-images.githubusercontent.com/64505309/90855587-a5816700-e388-11ea-8d7a-e0b1d3b2fd16.png)

**Environment**
 - VSCode Version: [e.g. 1.28.2]
 - OS Version: [e.g. Windows_NT x64 10.0.17134]

**Additional context**

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/4bc90fb9fe4421265df6b9fd711b53aa77755605
