### ISSUE TITLE
cpp compile won't launch

### ISSUE THREAD

**Issue by iamSlightlyWind** [danielpinto8zz6/c-cpp-compile-run#229]
Using my tab s6 with code-server running on termux - arrch64

my termux config:
- install andronix's ubuntu 20: `pkg update -y && pkg install curl proot tar -y && curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu/ubuntu.sh | bash`
- fully update: `apt-get update -y && apt-get dist-upgrade -y`
- get some additional package, including gcc: `apt-get install build-essential nano git curl -y`
- install code-server ( https://github.com/cdr/code-server): `curl -fsSL https://code-server.dev/install.sh | sh`
- start code-server, install `c-cpp-compile-run`, reload, create cpp file, press f6 to compile but nothing happens

since `cdr's code-server` installed and launched without any error, I believe this could be a problem related to your vscode's extension. Sorry if it was not

**Comment by danielpinto8zz6** [comment]
What's your vscode default terminal?

**Comment by iamSlightlyWind** [comment]
> What's your vscode default terminal?

neofetch showing it's using `vscode` terminal

**Comment by danielpinto8zz6** [comment]
it works if you change terminal?
btw, is gcc on your path?
