### ISSUE TITLE
Cannot Add Compiler Flags to Settings

### ISSUE THREAD

**Issue by FabianoGK** [danielpinto8zz6/c-cpp-compile-run#23]
The available settings are not showing the option for compiler flags:

![image](https://user-images.githubusercontent.com/1770086/46894575-fea21a80-ce42-11e8-8a5d-94d8474cb9e5.png)

Even when manually editing the user settings:

![image](https://user-images.githubusercontent.com/1770086/46894823-cbac5680-ce43-11e8-918b-37130742fe9f.png)

VS Code seems to be pulling a previous/older definition for the settings.

Environment:
* Linux:Ubuntu 14.04
* VS Code 1.28.1
* C/C++ Compile Run 0.2.7

**Comment by danielpinto8zz6** [comment]
I'll release a new version soon

**Comment by danielpinto8zz6** [comment]
fixed, 0.3.0 released
