### ISSUE TITLE
Add documents about configuration

### ISSUE THREAD

**Issue by xiechao06** [danielpinto8zz6/c-cpp-compile-run#231]
**Is your feature request related to a problem? Please describe.**
It cost me a lot of time to figure out how to configure the default compile flags by configuring "c-cpp-compile-run.cpp-flags". 

**Describe the solution you'd like**

describe configurations like "c-cpp-compile-run.cpp-flags".

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/b1c4888c9c42f4e2a8a1f26b37125f7212e8c874
