### ISSUE TITLE
Keyboard shortcut does not work in wsl 2

### ISSUE THREAD

**Issue by nsths** [danielpinto8zz6/c-cpp-compile-run#232]
Issue Type: <b>Bug</b>

Be on WSL 2 on the newest version of VS Code
press F6
nothing happens
change to WSL 1
press F6
code compiles and runs

Extension version: 1.0.11
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (7.31GB free)|
|Process Argv|--crash-reporter-id 4de1dc06-a3a3-44a8-ace0-6195121012ae|
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3499)|
|Memory (System)|12.25GB (11.19GB free)|
|VM|0%|
</details>

**Comment by danielpinto8zz6** [comment]
at the moment wsl2 is not supported, maybe in future release

**Comment by nsths** [comment]
Thanks! I had no idea. Have a good day!

**Comment by danielpinto8zz6** [comment]
I'll keep it open, as an enhancement for future release

**Comment by danielpinto8zz6** [comment]
Fixed with the support for the wsl
