### ISSUE TITLE
Run code with Free/Portable Embarcadero C++ Compiler

### ISSUE THREAD

**Issue by duytrung** [danielpinto8zz6/c-cpp-compile-run#234]
**Is your feature request related to a problem? Please describe.**
There is a compiler provided for free, suitable for C++ learner by Embarcadero (in free tools section). I'm wondering if C-Cpp Compile and Run can be configured with this compiler.

**Describe the solution you'd like**
Just compile and run as usual with Embarcadero C++ compiler (C++ Builder)
**Describe alternatives you've considered**
C++ compiler provided by Embarcadero is also a mature/productive compiler, should be supported as it's portablility and also as an alternative to gcc/mingw or microsoft C++ compiler (provided with Visual Studio).

**Additional context**

**Comment by danielpinto8zz6** [comment]
humm, not sure, you can try by settings the path and the flags
