### ISSUE TITLE
can't compile cpp file

### ISSUE THREAD

**Issue by April211** [danielpinto8zz6/c-cpp-compile-run#237]
First of all, thank you for developling this great tool! It helped me a lot!

But recently, when I want to compile a single cpp file by press F6, an error message comes out:
Command 'WMIC path win32_process get Name,Processid,ParentProcessId,Commandline,ExecutablePath' terminated with code: 44213
And this problem cannot be solved by reinstallation. What should I do?

1. New a cpp file with "Hello World" in Vscode
2. Press F6
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/53203590/102373045-c38b6b00-3ffa-11eb-832a-2eee45556746.png)

**Environment**
 - VSCode Version: 1.52.0
 - OS Version: Windows 10 20H2 19042.685
 - Mingw-w64 8.1.0

**Comment by danielpinto8zz6** [comment]
What's your gcc version?

**Comment by April211** [comment]
> What's your gcc version?

gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

**Comment by danielpinto8zz6** [comment]
It may be related to your gcc version, can you update it?

**Comment by April211** [comment]
> It may be related to your gcc version, can you update it?

I just updated my gcc, and it worked well on my device so far.
Thanks!

**Comment by danielpinto8zz6** [comment]
No problem 👍
