### ISSUE TITLE
Spelling for "Compiled successfully"

### ISSUE THREAD

**Issue by aditya2604** [danielpinto8zz6/c-cpp-compile-run#239]
**Issue: bug**
When the program has been successfully compiled, a small message appears on the bottom right which says, "Compiled successfuly!" The issue is that the word "successfuly" is spelled incorrectly: it should be spelled as "successfully" with two 'l's.

**Steps to reproduce the behavior:**
1. Compile any C++ file/project with the extension by pressing F6/F8
2. View the notification on the bottom right of the window
3. See the misspelled word

![image](https://user-images.githubusercontent.com/59426357/103471554-a5ca3f80-4d36-11eb-8134-a8c73a24acb5.png)

**Environment**
 - VSCode Version: 1.52.1
 - OS Version: Windows_NT x64 10.0.19041

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/487b6e1172b280171b8d61834becd3f77d4c3cdb
