### ISSUE TITLE
Microsoft/vscode#60820 : The developer tool pops up and triggers an error

### ISSUE THREAD

**Issue by Anti-Li** [danielpinto8zz6/c-cpp-compile-run#24]
# Bug Report

Only in [vscode 1.28.1](https://code.visualstudio.com/updates/v1_28).

## Details
The problem may be triggered because of the Run command.
But not due to this commit. 559594f has this bug too. Unknown vulnerabilities introduced time.
Still closed #21 temporarily for better error elimination.
Continue to pay attention to Microsoft/vscode#60820.

**Comment by Anti-Li** [comment]
![animation](https://user-images.githubusercontent.com/28052536/46901148-ab7ea500-cee0-11e8-80e8-a490202a933d.gif)

**Comment by danielpinto8zz6** [comment]
only happens if you're debbuging

**Comment by Anti-Li** [comment]
**But why happens when debugging?**

**Comment by danielpinto8zz6** [comment]
I don't know yet, something related with terminal I guess
