### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ahsansaif47** [danielpinto8zz6/c-cpp-compile-run#240]
- Issue Type: `Performance`
- Extension Name: `c-cpp-compile-run`
- Extension Version: `1.0.13`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\HABAD9~1.R\AppData\Local\Temp\danielpinto8zz6.c-cpp-compile-run-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by danielpinto8zz6** [comment]
What is your gcc version?

**Comment by ahsansaif47** [comment]
6.3.0

**Comment by danielpinto8zz6** [comment]
The extension uses gcc to compile the code, which causes high cpu load, so, this is related to gcc not extension itself

**Comment by ahsansaif47** [comment]
Thanks for your interest

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
