### ISSUE TITLE
Can't Compile/Run cpp file

### ISSUE THREAD

**Issue by XSkipperX** [danielpinto8zz6/c-cpp-compile-run#241]
Hi, thank you very much for this awesome tool.

But, for some reason it doesn't work anymore, whenever I press f6 it shows an error saying:
Running the contributed command: 'extension.CompileRun' failed.

New a cpp file in Vscode
Press F6
See error

**Screenshots**
![image](https://user-images.githubusercontent.com/61847271/104447226-c9de1a00-559b-11eb-9361-b1602d527da5.png)

Environment

- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.19042

**Comment by danielpinto8zz6** [comment]
Hi, are you using wsl 2?

**Comment by XSkipperX** [comment]
No, I don't, I couldn't figure out how to fix that so now I use atom for c++,

**Comment by danielpinto8zz6** [comment]
If you want to try again, please test with last mingw version
