### ISSUE TITLE
working slow

### ISSUE THREAD

**Issue by Vinitdr** [danielpinto8zz6/c-cpp-compile-run#244]
Issue Type: <b>Performance Issue</b>

This extension is loading very slowly. 

Extension version: 1.0.13
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (11.86GB free)|
|Process Argv|--crash-reporter-id e05a71eb-9a0e-493d-9ba0-819dfd05c3d5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    78	  5808	code main
    1	    51	  2080	   window (Issue Reporter)
    0	    68	  5144	   shared-process
    0	    25	  5436	   utility
    0	    12	 10960	   crashpad-handler
    0	   179	 13924	   gpu-process
    0	   155	 14552	   window (ques5.c - 18feb - Visual Studio Code)
    0	    13	  4608	     watcherService 
    0	    11	 11856	       console-window-host (Windows internal process)
    0	   107	 14232	     extensionHost
    0	    17	 13584	       c:\Users\KIIT\.vscode\extensions\ms-vscode.cpptools-1.2.1\bin\cpptools.exe
    0	    13	  4868	         c:\Users\KIIT\.vscode\extensions\ms-vscode.cpptools-1.2.1/bin/cpptools-srv.exe 13584 {955EFE3B-3397-4214-AC81-E50A988955C0}
    0	    11	  5352	         console-window-host (Windows internal process)
    0	    25	 14324	       electron_node serverMain.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ques5.c - 18feb - Visual Studio Code)
|    Folder (18feb): 11 files
|      File types: exe(5) c(5) txt(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by danielpinto8zz6** [comment]
This is because of the c compiler
