### ISSUE TITLE
Compile and Run in external console error

### ISSUE THREAD

**Issue by divz11** [danielpinto8zz6/c-cpp-compile-run#251]
### Error
Error while compile and running in external console using f8 in my Elementary OS.

`x-terminal-emulator isn't supported! Try to enter a supported terminal in 'terminal.external.linuxExec' settings! (gnome-terminal, xterm, konsole)`

**To Reproduce**
1. Open a cpp file in the Elementary OS VS code.
2. Write a simple short program.
3. Press F8 to 'Compile and Run in the External Console'.

**Expected behavior**
It should open the Elementary OS terminal (io.elementary.terminal) and compile and execute the program.

**Screenshots**
![C++ Error](https://user-images.githubusercontent.com/54148351/115194578-2beb7580-a0dd-11eb-9d89-476152adbeb0.png)

**Environment**
 - VSCode Version: 1.55.2
 - OS Version: Elementary OS 5.1.7 Hera

**Additional context**
It's working fine while compiling and running the file in the inbuilt terminal.

**Comment by danielpinto8zz6** [comment]
in `terminal.external.linuxExec set` value to `io.elementary.terminal` and try again please

**Comment by divz11** [comment]
Can you please let me know where as I am not understanding where to change.

**Comment by divz11** [comment]
I think there is something to change in extension.js Ln1 Col 45784.

**Comment by danielpinto8zz6** [comment]
In vscode settings

**Comment by divz11** [comment]
Yes it worked for me. Can you please add "Press any key to exit ..." at the end of the compilation ?

**Comment by danielpinto8zz6** [comment]
I don't think so, but I will take a look 👍
