### ISSUE TITLE
Sync Switch doesn't works

### ISSUE THREAD

**Issue by HotariTobu** [danielpinto8zz6/c-cpp-compile-run#253]
Issue Type: <b>Bug</b>

[settings-sync]

I use Windows and Mac.
I want to stop sync of settings the specific of extension but I cannot.

I can't set different values in "C-cpp-compile-run: C-flags" between the two machines.

VS Code: 1.55.2
Windows10: 20H2
Mac: 11.3

Extension version: 1.0.14
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500 6-Core Processor               (6 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (11.64GB free)|
|Process Argv|C:\\Users\\takato\\Desktop\\a.c --crash-reporter-id 21bc1b12-ece7-4b43-9737-5702b40767c9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by HotariTobu** [comment]
![SS](https://user-images.githubusercontent.com/24491003/116509848-ef025880-a8fe-11eb-937a-bb6d90848db5.png)

**Comment by danielpinto8zz6** [comment]
Hi, 
This extension doesn't have any sync feature

**Comment by HotariTobu** [comment]
Should I post to the VSCode repository?

**Comment by danielpinto8zz6** [comment]
do you use any extension to sync?

**Comment by HotariTobu** [comment]
I use the sync function of VS Code.

**Comment by HotariTobu** [comment]
Thank you to reply and this is the Settings Sync.
https://code.visualstudio.com/docs/editor/settings-sync
I finally solved the issue myself so I close this thread.

**Comment by danielpinto8zz6** [comment]
ok nice :+1:
