### ISSUE TITLE
The compile&run doesn't work,it will echo the file path. and can't see the warnings and errors content

### ISSUE THREAD

**Issue by Naishiro** [danielpinto8zz6/c-cpp-compile-run#26]
If I pressed F6, and it will compile but the run command is inside  double quotes like "path/to/binary/file", and which this command will echo the path, it will not run the file.

And the second issues is I can't see the wannings or errors specific content. it just show how many errors or warnnings generated.

**Comment by danielpinto8zz6** [comment]
can you provide screenshots?

**Comment by Naishiro** [comment]
![echo](https://user-images.githubusercontent.com/41794415/47649324-e9095080-dbb7-11e8-8bc6-e251d4e6676b.png)
![output](https://user-images.githubusercontent.com/41794415/47649325-e9a1e700-dbb7-11e8-98dc-e3de78906b4c.png)

this is the two issues,

**Comment by Anti-Li** [comment]
The first problem is because of you use Powershell. Let me specialize for it.

**Comment by Anti-Li** [comment]
@Naishiro Check your extension version.

**Comment by Naishiro** [comment]
@Anti-Li 0.3.0  ,

**Comment by Anti-Li** [comment]
@Naishiro This bug cannot be reproduced. There are specializations for Powershell in the code. At least the command should be & "a.exe" or cmd /c "a.exe". You can post the Integrated Terminal Path in your settings. And let me check.

**Comment by danielpinto8zz6** [comment]
it's not powershell problem, it doesn't compile into terminal, it compiles on its own, it only runs in terminal.

**Comment by Anti-Li** [comment]
@Naishiro Could you provide more information?

**Comment by Naishiro** [comment]
What information, just remove the double quotes and it will work ..

**Comment by danielpinto8zz6** [comment]
I guess it's fixed, I'll release soon
