### ISSUE TITLE
showing the "error: non-aggregate type" message

### ISSUE THREAD

**Issue by ishikkkkaaaa** [danielpinto8zz6/c-cpp-compile-run#260]
There is some problem with the extension I guess... i have added std=c++11 or std=c++17 parameter, but it doesn't add it even though it is configured. I can't directly run the file because this, every time i have to use `g++ -std=c++11 name.cpp`.

**Environment**

 - VSCode Version: Visual Studio Code 1.59.1
 - OS Version: macOS Catalina version 10.15.5 (cannot update due to storage issue, thus wasn't able to reinstall Xcode aswell)
 -  Extension Name: c-cpp-compile-run

command prompt message => 
`1-vector.cpp:9:17: error: non-aggregate type 'vector<int>' cannot be initialized with an initializer list
    vector<int> arr = {1, 2, 3, 4, 5, 10};
                ^     ~~~~~~~~~~~~~~~~~~~`

**Comment by danielpinto8zz6** [comment]
How have you added those flags?
