### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by DoidArthas** [danielpinto8zz6/c-cpp-compile-run#266]
When I press any of the keyboard shortcuts (f6, ctrl+6), nothing happens. MinGW is installed and is in PATH

1. Go to and .c or .cpp file
2. Press F6
3. Nothing Happens

It shouls compile and run the code at this point, Running by ctrl+shift+b and selecting gcc or g++ only compiles the code, and executing the .exe needs to be done manually in terminal

 - VSCode Version: 1.61.2
 - OS Version: Windows 10 21H1
 - g++ and gcc version: 9.2.0

**Comment by danielpinto8zz6** [comment]
Please check in the keyboard shortcut settings, if f6 is the current keyboard shortcut

**Comment by DoidArthas** [comment]
It is normally configured, but don't work. I've seem all configurations necessary, but it still with the problem.

**Comment by yummyX02** [comment]
> 它通常已配置，但不起作用。我似乎已经完成了所有必要的配置，但它仍然存在问题。

I have the similar question,when I express F6 ,nothing happened.However,if I express F8 or ctrl+6,their function are work.Thanks.

**Comment by danielpinto8zz6** [comment]
@yummyX02 other extension may be overriding the F6 shortcut
