### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Quirin1999** [danielpinto8zz6/c-cpp-compile-run#267]
Command 'WMIC path win32_process get Name,Processid,ParentProcessId,Commandline,ExecutablePath' terminated with code: 1

I can't get it to work. I get this error message every time. Any suggestions?

**Comment by zekyou** [comment]
Did you fix this problem? I also get this problem omg.

**Comment by 0xrabbyte** [comment]
This also happened on my computer.

**Comment by danielpinto8zz6** [comment]
What OS are you using?

**Comment by Quirin1999** [comment]
> What OS are you using?

Windows 11

**Comment by danielpinto8zz6** [comment]
Is that WSL2?
