### ISSUE TITLE
Your 131072x1 screen size is bogus. expect trouble

### ISSUE THREAD

**Issue by junn661** [danielpinto8zz6/c-cpp-compile-run#268]
**Describe the bug**
When running 'CompileRun: Compile' on WSL remote connection, I get an error message: 'your 131072x1 screen size is bogus. expect trouble'

**To Reproduce**
1. Open folder on WSL remote connection
2. Open C/C++ source file
3. Execute 'CompileRun: Compile with default/custom flags' (no problem with CompileRun: Run)

**Additional context**
Perhaps the problem is in find("name", proccess, true) at isProccessRunning(this.file.executable) at compiler.ts
![1](https://user-images.githubusercontent.com/18192378/145381476-edee5749-bd4b-4938-94c3-7abe3e071dfd.png)

**Comment by danielpinto8zz6** [comment]
is this wsl2?

**Comment by junn661** [comment]
> is this wsl2?

yes 

Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by danielpinto8zz6** [comment]
WSL2 is not supported yet
