### ISSUE TITLE
F6 is ineffective（windows10）

### ISSUE THREAD

**Issue by yummyX02** [danielpinto8zz6/c-cpp-compile-run#269]
**Describe the bug**
When I express the F6 ,it was ineffective.However,when I express ctrl+6 or F8 ,their function are work.

**Environment**
 - C/C++ Compile Run Version: [1.0.15]
 - OS Version: windows 10

**Comment by yummyX02** [comment]
expect your reply,thanks.

**Comment by danielpinto8zz6** [comment]
Hello,

You can check your keyboard shortcut settings and set keyboard shortcut to f6
