### ISSUE TITLE
The compiler path doesn't work.

### ISSUE THREAD

**Issue by Anti-Li** [danielpinto8zz6/c-cpp-compile-run#27]
When I set a compiler path like "C:\MinGW\bin\g++.exe" but not like "g++.exe", it will tell me "Compiler not found, try to change path in settings!".
However, setting compiler path "g++" and adding "C:\MinGW\bin" into PATH resolve the problem.
Is there some problem with npm module command-exists?

**Comment by danielpinto8zz6** [comment]
no, the compiler should be in the path if in vscode settings

**Comment by Anti-Li** [comment]
You mean I must add compiler path to PATH environmental variable?

**Comment by danielpinto8zz6** [comment]
no
check the code
the settings idea is to allow to specify diferent compilers, like using gcc on cpp files, so, its why we don't have a path for that but a full binary path

**Comment by Anti-Li** [comment]
So how to compile without adding compiler path to PATH environmental variable?

**Comment by danielpinto8zz6** [comment]
just add the gcc location to settings...

**Comment by Anti-Li** [comment]
Look at this viduo.
https://files.fm/u/kdcmmqqn

**Comment by Anti-Li** [comment]
![animation](https://user-images.githubusercontent.com/28052536/47601995-cede3f80-da0a-11e8-850e-b266f728986e.gif)
What's wrong with the module command-exists?

**Comment by danielpinto8zz6** [comment]
the path should be like : C://MinGW//bin//g++.exe

**Comment by Anti-Li** [comment]
No.
![index js - testcommandexists - visual studio code 2018_10_29 12_29_43](https://user-images.githubusercontent.com/28052536/47629683-8abc7d80-db77-11e8-99dd-02ea8727cbeb.png)

**Comment by danielpinto8zz6** [comment]
well, they remove the path, I guess the best option is to fork the command exists module and adapt for our own use

**Comment by danielpinto8zz6** [comment]
fixed https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/92fb2b105dd583dfaead8a7b41c6453bcefe62c0
