### ISSUE TITLE
Feature request related to External Terminal 

### ISSUE THREAD

**Issue by Sy0307** [danielpinto8zz6/c-cpp-compile-run#273]
This is Chinese. My English is not good. Please forgive me. I want to request to add a function. Now when running F6, CMD.exe will be run, but now I want to use windows terminal to run cmd.exe , i wanna it can be a option for "External terminal ".

Thank you!

**Comment by danielpinto8zz6** [comment]
Hi,

You just need to set your terminal to windows terminal and then set external terminal in the extension settings

**Comment by Jimihuazzz** [comment]
I have tried this method, but it seems that I can't do it under win10 system.

**Comment by danielpinto8zz6** [comment]
Hi, can you provide a bit more details?
