### ISSUE TITLE
[feat] custom run prefix

### ISSUE THREAD

**Issue by loynoir** [danielpinto8zz6/c-cpp-compile-run#287]
**Is your feature request related to a problem? Please describe.**
Current
```sh
$ ./foobar
```

Expected be able to run
```sh
$ valgrind --leak-check=yes ./foobar
```

**Describe the solution you'd like**
```
  "c-cpp-compile-run.run-prefix": "valgrind --leak-check=yes",
```

**Describe alternatives you've considered**

**Additional context**
Related https://github.com/danielpinto8zz6/c-cpp-compile-run/issues/282

**Comment by danielpinto8zz6** [comment]
Hi,

You can set custom run arguments already, c-cpp-compile-run.c-flags

https://github.com/danielpinto8zz6/c-cpp-compile-run#configurations

**Comment by loynoir** [comment]
@danielpinto8zz6 

```
    "c-cpp-compile-run.c-flags": "valgrind --leak-check=full",
```
means `gcc valgrind --leak-check=yes`, right?

```
    "c-cpp-compile-run.run-args": "valgrind --leak-check=full",
```
means `./program valgrind --leak-check=yes`, right?

Expect  `valgrind --leak-check=yes ./program`
