### ISSUE TITLE
A run command with parameters

### ISSUE THREAD

**Issue by Anti-Li** [danielpinto8zz6/c-cpp-compile-run#29]
Change the format of setting, just like the JS template string lets the user set the command with variables.

`"c-cpp-compile-run.run-command" = "gnome-terminal -e 'sh -c "${outputFile}; read -n1 -p "Press any key to continue...""'"`
Then we `getSetting<string>(key.runCommand).replace("${outputFile}", outputFile)` and run again.

_Originally posted by @Anti-Li in https://github.com/danielpinto8zz6/c-cpp-compile-run/pull/28#issuecomment-433908020_

**Comment by Anti-Li** [comment]
The same applies to compile parameters. So that we can
`wsl g++ ${sourceFile} -o ${outputFile}`
Especially effective for me.
It just happens to solve an unknown problem: after all the "-Wall -Wextra" of the running parameters in the settings are removed, it will magically compile and fail (not a compilation error).

**Comment by Anti-Li** [comment]
It just happens to solve an unknown problem: after all the "-Wall -Wextra" of the running parameters in the settings are removed, it will magically compile and fail (not a compilation error).

**Comment by danielpinto8zz6** [comment]
that doesn't make much sense, specifiyng the output file ..

**Comment by Anti-Li** [comment]
If we use this method, users only need to change this setting when the terminal isn't supported, instead of changing user's terminal.

**Comment by danielpinto8zz6** [comment]
that implies runing 2 terminals, plus I already added support for multiple terminals

**Comment by Anti-Li** [comment]
But you never know what kind of terminal the user is using. In case it is a new terminal, it is still valid for mine.

**Comment by danielpinto8zz6** [comment]
the user can choose a terminal already...

**Comment by Anti-Li** [comment]
But there's only gnome-terminal, xterm, and konsole, isn't it?

**Comment by danielpinto8zz6** [comment]
I have more locally. Will push soon
