### ISSUE TITLE
Error `Cannot read property 'clear' of undefined.`

### ISSUE THREAD

**Issue by Anti-Li** [danielpinto8zz6/c-cpp-compile-run#30]
**Describe the bug**
Pop up `Cannot read property 'clear' of undefined.` error
The clear command is undefined **at the very beginning**.

**To Reproduce**
Watch https://files.fm/u/kdcmmqqn.
Open Code, then run the extension.

**Expected behavior**
Expected not to pop up `Cannot read property 'clear' of undefined.` error.

**Screenshots**
![image](https://user-images.githubusercontent.com/28052536/47723721-16c1c880-dc90-11e8-8d9c-4e30ec67fb05.png)

**Comment by danielpinto8zz6** [comment]
yes, it looks like we need to wait a bit before clear

**Comment by Anti-Li** [comment]
This problem still occurs. I think await is not enough... It seems that there may still need a delay.
