### ISSUE TITLE
F5 Bug

### ISSUE THREAD

**Issue by HotariTobu** [danielpinto8zz6/c-cpp-compile-run#313]
The extension's F5 keybinding interferes with other languages' debugging triggers.

**To Reproduce**

1. Open (e.g.) .php file
2. Press F5
3. Notified "Invalid File!"

This also occurs when debugging.

**Expected behavior**

The function is not called when pressing F5 in others than the C/C++ files.

**Environment**
 - VSCode Version: 1.75.1
 - OS Version: Windows_NT x64 10.0.22621
 - C/C++ Compile Run Version: 1.0.36

**Comment by danielpinto8zz6** [comment]
Hi, fixed on version 1.0.38 👍
