### ISSUE TITLE
I can't work with the new Update

### ISSUE THREAD

**Issue by QuantumRevenant** [danielpinto8zz6/c-cpp-compile-run#317]
The new version automatically places the .exe in a file called output/ Is there a way to make the executable work like previous versions? (that the .exe appears next to the .cpp, in the same folder) I don't want to change the compile & run path every time I change projects. I tried to set the output path to "./", ".",".\",""./"", none work, I'm not the most skilled with this and the update made a perfectly useful extension, I found it make it impossible to use now. 
I'm going back to version 1.0.19, I'm not sure since when I get this error. I only know that since they added the new path to the .exe
I request support regarding this, if there is a way to do it and I don't know how, or place an option so that it works as previously.

**Comment by danielpinto8zz6** [comment]
So, you wan't to be able to compile and run in the same folder, without the output folder right?

**Comment by danielpinto8zz6** [comment]
@QuantumRevenant please update to the last version and make sure the output location setting is empty, it should work as you expect
