### ISSUE TITLE
Unable to use Zig cc compiler

### ISSUE THREAD

**Issue by dimaguy** [danielpinto8zz6/c-cpp-compile-run#319]
**Describe the bug**
I can't point the extension to use Zig's cc compiler because flags are placed after the file and output location are selected

**To Reproduce**
1. Set C-compiler to zig
2. Append cc to the beginning of C-flags
3. (optionally) set Cpp-compiler to zig and append c++ to beginning of Cpp-flags
4. Find that flags are placed after filenames, so it's all in vain

**Expected behavior**
Extension will invoke Zig's compilers as if they were gcc or clang

**Screenshots**
![image](https://user-images.githubusercontent.com/7207103/227785610-d54571d9-28ef-48ca-8b30-b1a74ef3d8f6.png)

**Environment**
 - VSCode Version: 1.76.2
 - OS Version: Windows 11 22H2

**Additional context**
I also attempted to append cc at the end of C-compiler, but that tries to find a binary named "zig cc" instead

**Comment by danielpinto8zz6** [comment]
Have you tried with gcc?

**Comment by dimaguy** [comment]
Yes, gcc works fine, but zig cc provides a more smooth cross compiling experience

**Comment by danielpinto8zz6** [comment]
what's the command to compile with zig?

**Comment by dimaguy** [comment]
> what's the command to compile with zig?

``zig cc (regular gcc flags)``
``zig g++ (regular clang flags)``

**Comment by danielpinto8zz6** [comment]
have you tried to put "zig cc" on your compiler?

**Comment by dimaguy** [comment]
> have you tried to put "zig cc" on your compiler?

I have, as I mentioned in the additional context, since it uses an exec call instead of a shell command call, it tries to look for a binary named zig cc, even if I renamed it, would make it so argv[0] would be "zig cc", and therefore, not recognized as the cc subcommand

**Comment by danielpinto8zz6** [comment]
@dimaguy I'll leave the issue open as an improvement for future release
