### ISSUE TITLE
Compiles but doesn't run

### ISSUE THREAD

**Issue by SuperSamus** [danielpinto8zz6/c-cpp-compile-run#32]
**Describe the bug**

**To Reproduce**
1. Open the file in VS Code
2. Do "Compile & Run"
3. The program is compiled (VS Code also says it in the bottom-right corner), but the terminal gives an error. Compile & run gives the command "cmd /c ./FileName.exe", but the terminal says that "." isn't a recognized command.

**Expected behavior**
The terminal should have executed the file. Probably the problem is in the command given to execute.

**Screenshots**
![image](https://user-images.githubusercontent.com/40663462/47885365-f121f400-de34-11e8-9425-2a7997975e16.png)
(Sorry for the italian language)

**Environment**
 - VSCode Version: 1.28.2
 - OS Version: Windows 10 x64 1809

**Additional context**
It didn't happen before the latest update.

**Comment by danielpinto8zz6** [comment]
Ill fix it today, thx

**Comment by Nexxkinn** [comment]
just switch it to .\ and the problem should be fixed.

**Comment by danielpinto8zz6** [comment]
It is already fixed

**Comment by danielpinto8zz6** [comment]
I just forgot to push, when I get home Ill push

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/e89d3f78f951ffb76d7c1d8eace752280c6f9368

**Comment by signorecello** [comment]
Hi Daniel.

On mac OSX:

![captura de ecra 2018-11-02 as 14 04 17](https://user-images.githubusercontent.com/20129824/47919787-3af7f200-dea8-11e8-8b66-3cf5f077b3bf.png)

Thank you!

**Comment by danielpinto8zz6** [comment]
@signorecello if you run only "index" in your console it works?

**Comment by signorecello** [comment]
Hi! Yes it is:

![captura de ecra 2018-11-04 as 00 05 50](https://user-images.githubusercontent.com/20129824/47965579-e471eb80-e040-11e8-890d-ed84e84f11ca.png)

**Comment by danielpinto8zz6** [comment]
it is fixed now, update your extension and try again
