### ISSUE TITLE
Change the position of compilation flags for precompiled headers

### ISSUE THREAD

**Issue by joshi248** [danielpinto8zz6/c-cpp-compile-run#327]
**Using different c++ standard doesn't actually changes the compilation of program but changes the execution of it.**

**Note: I have changes the keybinding of compile and run to Ctrl + 1.
**To Reproduce**
1. Press Ctrl + 1 or keybinding for compiling the program. Note here I am saying 'compiling' and not 'compiling and running'.
**Expected behavior**
As seen in the below image the compilation flags appear after the executable file name, BUT IT SHOULD BE APPEARING AFTER SOURCE FILE NAME i.e., AFTER .cpp.

**Screenshots**
![image](https://github.com/danielpinto8zz6/c-cpp-compile-run/assets/109964271/4475e85d-f4fc-47ae-9cc8-d861f03280e5)

**Environment**
 - VSCode Version: latest
 - OS Version: [e.g. Windows_10 x64 22.134]

**Additional context**
Maybe tell us a way to bring compilation flags after the .cpp file name and not after the executable name.
I am saying this because many programmers use precompiled headers for fasten up the compilation but this thing takes a lot of time for compilation

**Comment by danielpinto8zz6** [comment]
Hello,

Can you check if the error persists with version **1.0.46**?

**Comment by joshi248** [comment]
yeah it works
