### ISSUE TITLE
g++.exe: fatal error: cannot read spec file 'libsanitizer.spec': No such file or directory

### ISSUE THREAD

**Issue by RainPPR** [danielpinto8zz6/c-cpp-compile-run#328]
English (Machine translation): Please put quotation marks (`"`) around the file name in the compile instruction. I had an error compiling **a file with a space in the file name** with gcc (`g++.exe: fatal error: cannot read spec file 'libsanitizer.spec': No such file or directory`).

请在编译指令中在文件名的两侧加上引号（`"`），我在用gcc编译一个**文件名中带有空格**的文件时出现了错误（`g++.exe: fatal error: cannot read spec file 'libsanitizer.spec': No such file or directory`）。

Thanks.

**Comment by danielpinto8zz6** [comment]
Hello,
So your file has a space in its name?

**Comment by RainPPR** [comment]
> Hello, So your file has a space in its name?

Yes, such as "T1235 sort.cpp"

**Comment by danielpinto8zz6** [comment]
Please avoid using file names with spaces, that's the cause of your problem
