### ISSUE TITLE
 '. ' is not an internal or external command, nor a runnable program. 

### ISSUE THREAD

**Issue by unkn0wn9** [danielpinto8zz6/c-cpp-compile-run#33]
**Describe the bug**
When and use this extensions in my program , after compile , when it tried to run this program , it shows : '. ' is not an internal or external command, nor a runnable program. 
In terminal , the command is ' cmd /c ./xxxx.exe' 

**Environment**
 - VSCode Version: 1.28.2
 - OS Version: Windows10 1803
 - GCC: MINGW32-W64 8.1.0

**Comment by danielpinto8zz6** [comment]
Fixed https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/e89d3f78f951ffb76d7c1d8eace752280c6f9368
