### ISSUE TITLE
Chinese garbled characters problem

### ISSUE THREAD

**Issue by paeonia-lactiflora** [danielpinto8zz6/c-cpp-compile-run#331]
Without any malicious intent, I just want to ask if anyone knows how to solve the problem of garbled Chinese characters?
![image](https://github.com/danielpinto8zz6/c-cpp-compile-run/assets/124262436/76e288d7-1f64-4a00-a6aa-f42840ecb71f)

**Comment by LHyphen** [comment]
插件设置里 C-flags 和 Cpp-flags 加上 `-fexec-charset=GBK`
![image](https://github.com/danielpinto8zz6/c-cpp-compile-run/assets/83161242/995d0967-f552-4ab2-9511-99a53f7586e9)

**Comment by Xinli-GUMP** [comment]
> 插件设置里 C-flags 和 Cpp-flags 加上 `-fexec-charset=GBK` ![image](https://user-images.githubusercontent.com/83161242/263526776-995d0967-f552-4ab2-9511-99a53f7586e9.png)

会报错：cc1plus.exe: error: no iconv implementation, cannot convert from GBK to UTF-8
