### ISSUE TITLE
Seriously slows down compilation

### ISSUE THREAD

**Issue by RimuruChan** [danielpinto8zz6/c-cpp-compile-run#339]
https://github.com/danielpinto8zz6/c-cpp-compile-run/blob/8e2664d0d46f6ad333864955867bf51573a364b5/src/utils/common-utils.ts#L11

This check operation takes too long on Windows and takes several seconds.

**Comment by danielpinto8zz6** [comment]
hi, 
I can temporary disable this on windows, until I find a better solution for this

**Comment by danielpinto8zz6** [comment]
@RimuruChan can you check if the error persists with this version? https://transfer.sh/1f1fgkrzEY/c-cpp-compile-run-1.0.51.vsix
