### ISSUE TITLE
Need help with the execution time of the .exe

### ISSUE THREAD

**Issue by AimbotNooby** [danielpinto8zz6/c-cpp-compile-run#340]
**Describe the bug**
When I compile and run the .exe with the extension the execution time of the .exe is very slow.
But when I execute the file manually it will give an instant output.

Btw I've had the same problem with CodeRunner.

**Comment by danielpinto8zz6** [comment]
You're on windows right?

**Comment by AimbotNooby** [comment]
Yes

**Comment by danielpinto8zz6** [comment]
@AimbotNooby can you check if the error persists with this version? https://transfer.sh/1f1fgkrzEY/c-cpp-compile-run-1.0.51.vsix

**Comment by AimbotNooby** [comment]
Unfortunately not. Running the exe still is quite slow.

**Comment by danielpinto8zz6** [comment]
So, I think the slow down is related to windows defender or your anti-virus scanning the exe before running it

**Comment by AimbotNooby** [comment]
Oh great thank you! It was my anti-virus tool.
