### ISSUE TITLE
Need help with building a project that has multiple .cpp files

### ISSUE THREAD

**Issue by dev2pew** [danielpinto8zz6/c-cpp-compile-run#341]
How to tell extension that I want to compile multiple files?

On compiling, it throws an error:
`collect2.exe: error: ld returned 1 exit status`

I've managed to set up the `tasks.json` file for building a project, and it's working with the default compiler.
![image](https://github.com/danielpinto8zz6/c-cpp-compile-run/assets/65161490/0e9224b1-6173-477a-91d3-9b5391adf4d8)

However, I'd rather use your extension instead of the default one. Do you have any suggestions?

**Comment by danielpinto8zz6** [comment]
You can try to add the other files to compile flags
