### ISSUE TITLE
When I press F5, there is no response, the plug-in cannot be used, and there is no prompt.

### ISSUE THREAD

**Issue by L-Macy** [danielpinto8zz6/c-cpp-compile-run#343]
When I press F5, there is no response, the plug-in cannot be used, and there is no prompt.
[Uploading Desktop 2023.11.06 - 17.54.23.01.zip…]()

**Comment by danielpinto8zz6** [comment]
Try with F6

**Comment by m735428610** [comment]
The same

**Comment by danielpinto8zz6** [comment]
What OS are you using?

**Comment by m735428610** [comment]
win11 23H2

**Comment by m735428610** [comment]
Uploading Desktop 2023.11.06 - 17.54.23.01.mp4…

**Comment by m735428610** [comment]
[Uploading Desktop 2023.11.06 - 17.54.23.01.zip…]()

**Comment by L-Macy** [comment]
I don't know why pressing F6orF5 doesn't work, is it a problem with the system.

**Comment by danielpinto8zz6** [comment]
if you try to use the extension from command pallet it works?

**Comment by L-Macy** [comment]
no

**Comment by danielpinto8zz6** [comment]
Try to uninstall and reinstall the extension again

**Comment by L-Macy** [comment]
No

**Comment by danielpinto8zz6** [comment]
Try to delete the extensions cache, and reinstall vscode
