### ISSUE TITLE
I hope to add a custom output address to the exe file

### ISSUE THREAD

**Issue by meng-ru-nan-fa** [danielpinto8zz6/c-cpp-compile-run#345]
**Is your feature request related to a problem? Please describe.**

There is a file address a \ b \ main.cpp
Run by default, the exe file will be generated in a \ b \ output \ main.exe
But I want to generate it in a \ output \ main.exe
However, in the plugin settings of vscode, the highest can only be set to the directory where the CPP file is located

**Describe the solution you'd like**

I hope to customize the generated file directory like the tasks.json file in VSCode.For example, by using parameters such as ${workspaceFolder}
![image](https://github.com/danielpinto8zz6/c-cpp-compile-run/assets/72238162/47ac11ff-7257-4182-a1a4-b58049afb511)

**Comment by danielpinto8zz6** [comment]
Hi, you can pass a full path for the output location, like: /home/user/output

**Comment by meng-ru-nan-fa** [comment]
Thanks for your answer. And I will provide a detailed explanation of my demands. 
The following paragraph was translated by a translator, and the description may be a bit verbose. Please don't mind it.

What I want is a path description method that shares the same solution as the`launch. json` in vscode such as `${workspaceFolder}`
This may be a niche feature, but I'm not sure.

Here‘s an example for better description
1. open `E:\projects\A` in vscode
2. compile `E:\projects\A\task\example1.cpp`
If fill the blank with `output`, the exe file will be generated in `E:\projects\A\task\output`
If fill the blank with `E:\projects\A\output` , the exe file will be generated in `E:\projects\A\output`
3. open `E:\projects\B`
4. compile `E:\projects\B\task\example2.cpp`
the  exe file will still be generated in `E:\projects\A\output` instead of the expected location `E:\projects\B\output`

In my thought, it would be easy to solve this problem by filling in `${workspaceFolder}\output`
![image](https://github.com/danielpinto8zz6/c-cpp-compile-run/assets/72238162/89e66edf-ed7d-4933-8d11-acb0e5de1f9a)
