### ISSUE TITLE
"Wsl detected, running in vscode terminal!" while running in external terminal

### ISSUE THREAD

**Issue by Hussain-Ali-12** [danielpinto8zz6/c-cpp-compile-run#352]
**Describe the bug**
I am encountering this error "Wsl detected, running in vscode terminal!" when running my c++ code in external terminal even though nothing related to WSL is installed either in my VS Code or Windows.

Note: This problem is only occurring in extension version 1.0.53 and onwards 

**To Reproduce**
1. Open any program (c++ program in my case)
2. Press F8 or click on  'Compile & Run' at the bottom left of VS Code's Status Bar
3. A warning notification with message "Wsl detected, running in vscode terminal!" will appear at the bottom right of VS Code's interface

**Expected behavior**
The program will run in integrated terminal instead of external console

**Screenshots**
![error](https://github.com/danielpinto8zz6/c-cpp-compile-run/assets/153849846/03912c4c-0289-4468-abae-aa456d624141)

**Environment**
 - VSCode Version: 1.86.0
 - OS Version: Windows 11 Home 22H2 

**Additional context**
The program is running fine in external console in extension version 1.0.50 and older versions, i am encountering this problem only in recent releases of the extension

**Comment by danielpinto8zz6** [comment]
Can you please try the new version v1.0.57? https://github.com/danielpinto8zz6/c-cpp-compile-run/releases/tag/v1.0.57

**Comment by Hussain-Ali-12** [comment]
I have tried that as well, still got the same error

[image: image.png]

**Comment by danielpinto8zz6** [comment]
Ok, I think now it's working, version 1.0.58 https://github.com/danielpinto8zz6/c-cpp-compile-run/releases/tag/v1.0.58

**Comment by Hussain-Ali-12** [comment]
Yes, it is working now...
I am grateful for your help.

[image: image.png]
