### ISSUE TITLE
Questions about debugging

### ISSUE THREAD

**Issue by gyqljs** [danielpinto8zz6/c-cpp-compile-run#355]
This is what's inside my launch.json file
{
  version "0.2.0".
  "configurations": [
    {
      "name": "launch!" ,
      "type": "cppdbg",
      "request": "startup",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],.
      "stopAtEntry": false,
      "cwd": "${fileDirname}",
      "environment": [],.
      "externalConsole": true,
      "MIMode": "lldb",
      "preLaunchTask": "C/C++: clang++ Generate active file",
      "miDebuggerPath": "/usr/bin/lldb".
    }, .
    
  ]
}
The path to lldb is correct
But why is it always
Cannot start debugging. The startup option string provided by the project system is invalid. The path to the debugger could not be determined. Please specify the "MIDebuggerPath" option.

Translated with DeepL.com (free version)

**Comment by danielpinto8zz6** [comment]
Hi, do you have gdb installed?
