### ISSUE TITLE
Custom linux terminal request

### ISSUE THREAD

**Issue by Anik200** [danielpinto8zz6/c-cpp-compile-run#359]
**Is your feature request related to a problem? Please describe.**
is there any way i can use a custom terminal to get my c++ output eg. kitty (im on void linux and by far enjoying your extension)

**Describe the solution you'd like**
atm i can only use gnome-terminal, konsole and xterm but i really want to know if i can use kitty

**Describe alternatives you've considered**

**Additional context**

**Comment by danielpinto8zz6** [comment]
Hi @Anik200 , at the moment the extension doesn't support custom terminals, neither kitty, 
Supported terminals for linux are: xterm, gnome terminal, elementaryOS terminal, mate terminal, xfce4 terminal and konsole

**Comment by Anik200** [comment]
I could have used Konsole but when i kill the output or  the execution
stops it doesn't show `press any key to continue` is it possible to enable
it on konsole too ?

**Comment by danielpinto8zz6** [comment]
I haven't found a way to open koncole and wait before program execution, in case you know how to do it, just ping me
https://github.com/danielpinto8zz6/c-cpp-compile-run/blob/master/src/external-terminal.ts#L70
