### ISSUE TITLE
To add support for CPP 11+ versions

### ISSUE THREAD

**Issue by adityahongal** [danielpinto8zz6/c-cpp-compile-run#360]
The C++ Compiler doesn't support vector initialization like in CPP 11+ versions.

Example : - In CPP 11+ version, we can directly declare as vector< int > nums = {1,2,3,4};

But your compiler causes as error due to this and doesn't compile

so we need to manually push_back

Please do update/give support to CPP 11+ versions

**Comment by danielpinto8zz6** [comment]
It's not a problem related to this extension but with the cpp compiler you're using
