### ISSUE TITLE
Add Suffix option in 'Extensions Settings'

### ISSUE THREAD

**Issue by murielgodoi** [danielpinto8zz6/c-cpp-compile-run#362]
**Is your feature request related to a problem? Please describe.**
Programmers are unable to add compilation parameters that should be placed at the end of the command, e.g., -lm.
"Compiler flags" come after gcc or g++, so it doesn't work for that purpose.

**Describe the solution you'd like**
Add an extra field in the 'Extensions Settings' labeled 'suffix' to allow the setting of that parameter.

**Comment by Welding-Torch** [comment]
+1 Can't compile because of this

**Comment by sazid1183** [comment]
Yes. I am also unable to compile because can't use -lm!
