### ISSUE TITLE
Bug when having trailing spaces in compiler flags

### ISSUE THREAD

**Issue by zlate42** [danielpinto8zz6/c-cpp-compile-run#37]
**Describe the bug**
If there are one or more trailing space-characters in the flags configuration, you get an error when trying to compile and run with F6

**To Reproduce**
1. Go to Settings
2. Add just one space to the C-flags (i did not test with Cpp-flags)
3. try to compile a c-file with F6
4. you get: gcc: error: : No such file or directory
5. remove trailing space from flag settings, everything works fine again.

**Environment**
 - VSCode Version: [e.g. 1.29]
 - OS Version: Windows 10 x64

**Additional context**
I am not good at Javascript, but my guess is that the trim() function could help here

**Comment by danielpinto8zz6** [comment]
hi, thanks for reporting,
yes trim() will solve it,
I am busy today, tomorrow I'll take a look

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/6fedcc57af03cd4853c9cf5803c3fc4a319bd273
