### ISSUE TITLE
Cannot run on windows when using Powershell

### ISSUE THREAD

**Issue by TremblingMoeNew** [danielpinto8zz6/c-cpp-compile-run#38]
**Describe the bug**
For example, I'm just trying to compile and run HelloWorld.cpp
Powershell just cannot execute "HelloWorld.exe" but directly print it out as a string
The command should be ./"HelloWorld.exe" 

**To Reproduce**
1. Confirm that current Windows shell is Powershell
2. Open the file in VS Code 
3. Do "Compile & Run"
4. Your terminal prints out the name of the execuatble file
5. Open Powershell, cd to the file's dictionary, enter the file name with quotation marks. Powershell prints it out.
6. Enter the file name without quotation marks. Powershell warns that the command not found but the file did exist, and hints that you can add a '.\' ('./' works too) before the file name to exec.
7. add './' before (the file name with quotation masks) and try to exec again. It works.

**Solution**
Use the same execute command as on Linux or macOS when using Powershell 

**Environment**
 - VSCode Version:  1.28.2
 - OS Version:  Windows_NT x64 10.0.17134
 - Powershell Version: 5.1.17134.407
 - Extension Version: 0.4.3

**Comment by danielpinto8zz6** [comment]
Hi, thanks for report, 
I'll take a look this night

**Comment by danielpinto8zz6** [comment]
So, you're using internal or external console?

**Comment by TremblingMoeNew** [comment]
Internal

**Comment by TremblingMoeNew** [comment]
>           So, you're using internal or external console?

Internal

**Comment by danielpinto8zz6** [comment]
I guess it is working fine now, please check
