### ISSUE TITLE
Compiles but doesn't run files with spaces in their name in external terminal

### ISSUE THREAD

**Issue by SuperSamus** [danielpinto8zz6/c-cpp-compile-run#39]
**Describe the bug**
It's the same as Issue #34, but for the external terminal (ticked in the extension config).

**To Reproduce**
1. Go to settings and tick Run-in-external-terminal in the extension config.
2. Same as Issue #34.

**Expected behavior**
Same as Issue #34.

**Comment by danielpinto8zz6** [comment]
do you have your extension and your vscode updated?

**Comment by SuperSamus** [comment]
Yes, I have.
With the internal terminal it executes files with spaces in their name.
With the external terminal it doesn't (probably because of the absence of quotes when doing the command).
