### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Silver2410** [danielpinto8zz6/c-cpp-compile-run#4]
When pressing the key "F6" to compile the file 'hello.c', my console displays the following command:

`gcc -Wall -Wextra 'd:\workspace\C\hello-world\hello.c' -o 'd:\workspace\C\hello-world\hello'`

```
gcc: error: 'd:\workspace\C\hello-world\hello.c': Invalid argument
gcc: fatal error: no input files
compilation terminated.
```

causing an error; instead of the single quote marks ( ' ) to deliminate the paths, the double quotes ( " ) should be used instead.

**Comment by Silver2410** [comment]
also, " 'clear' is not recognized as an internal or external command" yada yada yada.

By selecting 'Powershell' as default shell, the result is the following:

```
D:\workspace>& gcc -Wall -Wextra 'd:\workspace\C\hello-world\hello.c' -o 'd:\workspace\C\hello-world\hello'
& unexpected.

D:\workspace>& clear
& unexpected.

D:\workspace>& 'd:\workspace\C\hello-world\hello'
& unexpected.
```

Using Win10 17134.167,
VS Code 1.25.1

**Comment by BDZNH** [comment]
@Silver2410 wait for a update.
For some detail in [https://github.com/danielpinto8zz6/c-cpp-compile-run/pull/5](https://github.com/danielpinto8zz6/c-cpp-compile-run/pull/5)

**Comment by BDZNH** [comment]
@Silver2410 You can download it [https://github.com/BDZNH/c-cpp-compile-run/releases](https://github.com/BDZNH/c-cpp-compile-run/releases)

it is ok on windows with g++.

**Comment by Silver2410** [comment]
works great now, thanks :)

do you think it will possible in a future version (if you're still willing to work on it, don't want to stress you) to make it compile everything but make it run only the currently selected .c file? Like, "press F6 to compile and run everything", or "Shift + F6 to compile everything and run the file you're currently editing".

But I'm not very used to C and organize my work poorly, so probably I'm just asking a question about a problem that people who actually benefit from your extension don't have.

Thank you very much again, I really appreciate your work!

**Comment by danielpinto8zz6** [comment]
Should be fixed now, try it
