### ISSUE TITLE
(Suggestion) Warning when compiling while running

### ISSUE THREAD

**Issue by SuperSamus** [danielpinto8zz6/c-cpp-compile-run#40]
**Is your feature request related to a problem? Please describe.**
When you try to compile while the program is running gives the error "collect2.exe: error: ld returned 1 exit status". This is related to GCC of course. However, this sometimes happens because you forgot to close the terminal that was running the program, and seeing this error might let you wonder what is this.

**Describe the solution you'd like**
If you try to compile while the program is running, the extension will warn you that you have to close the terminal. Maybe in the notification area in the bottom right area it could ask you if you prefer to close the terminal automatically or to abort the compilation, and in the extension configuration add the option to choose if you always want to choose or to always do one of the two.

**Comment by danielpinto8zz6** [comment]
Hi,
I don't know if this should be considered a bug, plus I don't know if we should close the terminal.
Note that you can even have the binary opened in another terminal external do vscode.
I think that's up to user to handle thoose situations

**Comment by SuperSamus** [comment]
Well, GitHub issues are also for suggestions (when opening an issue it asks you if you want the bug template or the suggestion template).
Anyway, I think that at least it should say that it can't compile beacuse that program is in execution in one of the VSCode terminals (maybe the user clicked the cross instead of the bin and might think he closed the terminal when he actually hid it). And since that GCC error isn't very clear, let the extension be.

**Comment by danielpinto8zz6** [comment]
Yeah, it makes sense show some better information. I'll take a look. Thanks
