### ISSUE TITLE
Debug support.

### ISSUE THREAD

**Issue by andylizf** [danielpinto8zz6/c-cpp-compile-run#46]
Feature:
When I click "debug" button, it will compile my program and run. Like what it do when I press F6.
Need single file debug api.

**Comment by Anti-Li** [comment]
I mean we can click debug button, and the effect is as the same as clicking F6.

**Comment by danielpinto8zz6** [comment]
Yes, but that's for a different purpose, that debug tool can debug whole project, this is just for debug single pages

**Comment by Anti-Li** [comment]
The is api support to debug a single file.

**Comment by Anti-Li** [comment]
People click debug button but actually want to run them. We needn't deal with the breakpoints.
Many extensions do as this.

**Comment by danielpinto8zz6** [comment]
yes but people may wan't to have both, like debug and quick run

**Comment by Anti-Li** [comment]
Clicking debug button means quick running here.

**Comment by danielpinto8zz6** [comment]
the debug tool is more complex, people may need it to debug the program, this is only a quick compile run for small projects, we shouldn't mix it

**Comment by danielpinto8zz6** [comment]
Added debug support
