### ISSUE TITLE
A small problem

### ISSUE THREAD

**Issue by ILSYT** [danielpinto8zz6/c-cpp-compile-run#47]
VSCode v1.30.2
Windows7 64bit
When I compile a C++ file for the first time, if there are any compile errors, the extension will close the editor. I think there must be something wrong in the extension. Can you help me?

**Comment by ILSYT** [comment]
@danielpinto8zz6 Yes. I use MinGW-w64 8.1.0. I'll send an email to you.

**Comment by danielpinto8zz6** [comment]
So, I've seen your video, that may be happening because the file is not saved, did you tried with saved file?

**Comment by ILSYT** [comment]
Well, when I push F6 ,VSCode ask me to save the file. After the error compiling, the editor is closed, but the file has been saved.

**Comment by ILSYT** [comment]
I tried prohibit other extensions to avoid the conflict. But when I run the extension, the editor closed again.

**Comment by ILSYT** [comment]
Yes. Just when I save and compile the file for the first time.

**Comment by danielpinto8zz6** [comment]
So, in order to compile correctly we need to make sure that file is saved, I added an error message to prevent that kind of bugs.
Thanks

**Comment by ILSYT** [comment]
@danielpinto8zz6 OK, thanks very much.
