### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by dustast** [danielpinto8zz6/c-cpp-compile-run#48]
![image](https://user-images.githubusercontent.com/24965656/51805065-ed84ea00-2236-11e9-8f01-bf1845ffe879.png)

I am trying to switch from code blocks to VS Code but I am getting a compile error. Also the past issues did not help me much.

**Comment by Morwenn** [comment]
I get the same, and no way to find the actual compiler output to know while the compilation failed.

**Comment by danielpinto8zz6** [comment]
try mingw instead of codeblocks mingw
https://sourceforge.net/projects/mingw/

**Comment by Morwenn** [comment]
I'm using MinGW-w64, straight from SourceForge.

**Comment by factoryal** [comment]
is anyone solved this problem?
I also stuck at here.
Win10 1903, MinGW installed, writted right compiler path.

**Comment by factoryal** [comment]
Hey, I just solved this problem simply adding gcc location to PATH.
works very nice right now.
also, my gcc location is => C:\MinGW\bin\gcc.exe

**Comment by danielpinto8zz6** [comment]
Hi, glad you fixed it :+1:
