### ISSUE TITLE
I can't use the key"F6"

### ISSUE THREAD

**Issue by yltx** [danielpinto8zz6/c-cpp-compile-run#50]
Issue Type: <b>Bug</b>

I can't use the key"F6"

I have already had everything down,but it's still useless.

my c_cpp_properties.json is 

```json
{
    "configurations": [
        {
            "name": "Win64",
            "intelliSenseMode": "clang-x64",
            "compilerPath": "C:/Mingw/bin/g++.exe",
            "includePath": [
                "C:/MingW/lib/gcc/mingw32/6.3.0/include/c++/*",
                "C:/MingW/include/*",
                "C:/MingW/lib/gcc/mingw32/6.3.0/include/*",
                "C:/MingW/lib/gcc/mingw32/6.3.0/include/c++/*",
                "C:/MingW/lib/gcc/mingw32/6.3.0/include/c++/backward/*",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/tr1",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/ext/pb_ds",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32/bits"
            ],
            "defines": [],
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17",
            "clang.executable": "clang",
            "clang.completion.enable": true,
            "clang.cxxflags": [
                "-std=c++11",
                "C://Mingw//lib//gcc//mingw32//6.3.0//include//c++"
            ]
        }
    ],
    "version": 4
}
```

Extension version: 0.4.3
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by VickyAbishek** [comment]
Having the same issue here. On Mac OS.

**Comment by yltx** [comment]
@VickyAbishek link?

**Comment by VickyAbishek** [comment]
> @VickyAbishek link?

Can't understand. I am personally facing this. Link for what?

**Comment by jhcccc** [comment]
Hello, macOS user here. Doesn't work for me either. The key I press is "Fn+F6" because on a Mac "F6" adjusts keyboard backlight and "Fn+F6" is the real functional key. However, when I press this, nothing happens, the code is not compiled.

**Comment by yltx** [comment]
@VickyAbishek Oh, sorry, I'm wrong.

**Comment by danielpinto8zz6** [comment]
Hi guys, sorry I don't have a mac where I can test, just say a key that should work and I send you a testing version

**Comment by LazyRen** [comment]
Hello everyone, for those who could not solve the issue,
default keybinding for mac is a bit different from other OS.
compile & run : cmd + r
compile & run with custom argvs : cmd + t.

**Comment by yltx** [comment]
But did anybody notice my question?I use Windows10

**Comment by danielpinto8zz6** [comment]
Did you updated your extension and have gcc installed?

**Comment by yltx** [comment]
@danielpinto8zz6 Yes

**Comment by jhcccc** [comment]
@LazyRen that worked for me perfectly! thanks

**Comment by happyangry** [comment]
@LazyRen  It works! thanks!

**Comment by danielpinto8zz6** [comment]
Nice, thanks @LazyRen
