### ISSUE TITLE
I hope that it don't clear the former things on terminal everytime I use it. ;)

### ISSUE THREAD

**Issue by XZJIsme** [danielpinto8zz6/c-cpp-compile-run#51]
Just like the extension code runner, but it can't be compatible with my chinese。please
also hope that my poor english express is appropriate...

**Comment by XZJIsme** [comment]
I‘ve installed old version。your extension is very easy and good to use， thank you very much！

**Comment by danielpinto8zz6** [comment]
Hi, it's fixed on last version :+1: 
Thank you
