### ISSUE TITLE
Breakpoints missing

### ISSUE THREAD

**Issue by Filliny** [danielpinto8zz6/c-cpp-compile-run#52]
**Is your feature request related to a problem? Please describe.**
- Problem is wrong compiling string in \out\CompileRun.js that  leads to missing breakpoints for debugging in output file.

**Describe the solution you'd like**
need add simple '-g' in compile string 

line 33
`           let exec;
            let compilerArgs = ['-g', file.$name, '-o', file.$executable];
            let compilerSetting;
            let compilerSettingKey;`

**Describe alternatives you've considered**
Hardest way is to implement additional parameter "compiler string" - to be able add anything else ... or read included in project file tasks,json for "args" string but here we have another dificulty when tasks >1 :-)

**Comment by danielpinto8zz6** [comment]
Hi, this is not supposed to be used for debbing, only for compile and run
