### ISSUE TITLE
How can i compile and run my c programming file in visual studio code?

### ISSUE THREAD

**Issue by Sahilrajput1** [danielpinto8zz6/c-cpp-compile-run#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - VSCode Version: [e.g. 1.28.2]
 - OS Version: [e.g. Windows_NT x64 10.0.17134]

**Additional context**

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/blob/master/README.md#how-to-use
