### ISSUE TITLE
a smal bug in runing code

### ISSUE THREAD

**Issue by aliraza7926** [danielpinto8zz6/c-cpp-compile-run#57]
when I press f6 code compiles successfully but it doesn't run

as you can see it must be .\test.exe but it is "test.exe"  and it can't run

![Screenshot (229)](https://user-images.githubusercontent.com/37420563/59277967-5d3fc280-8c76-11e9-8405-36bdceb6a39d.png)

 - VSCode Version: 1.35.0
 - OS Version:  Windows_NT x64 10.0.17134

**Comment by ViniciusSSilva** [comment]
I was having the same issue, this worked for me:
- Press: Ctrl+Shift+P
- Search: "Terminal: Select Default Shell"
- Select the powershell option

I guess that on this new VSCode update it changed to Git as default shell so the extension doesn't uses the cmd /c

**Comment by eagskunst** [comment]
@ViniciusSSilva solution worked for me. But changing the default shell could make other extension/vs code to fail or not work properly? I don't know if there is a way to detect which Bash is selected as default by the user so the extension could properly execute the 2nd command.

**Comment by aliraza7926** [comment]
@ViniciusSSilva  it is work thanks a lot
