### ISSUE TITLE
compile but doesn't run, just print .exe filename

### ISSUE THREAD

**Issue by CyberFlower** [danielpinto8zz6/c-cpp-compile-run#60]
![image](https://user-images.githubusercontent.com/44886886/61436261-627ae600-a975-11e9-8704-e37447a6199c.png)"
When I write a code test.cpp and hit F6, it compiles but print test.exe
My code is just print "hello world", as you can see!

**Comment by akash-258** [comment]
same problem here , HELP

**Comment by akash-258** [comment]
Found solution : Just enable "run in a new external terminal" option in extension settings and it will work

**Comment by Jhonatan-Holanda** [comment]
mesmo problema aqui, to usando do jeito que o @akash-258 mencionou, mas queria utilizar o do próprio vscode.
