### ISSUE TITLE
Output execute time

### ISSUE THREAD

**Issue by zryabc** [danielpinto8zz6/c-cpp-compile-run#62]
I am an algorithmic contestant. The execute time of the program is very important to me, so I want to know the execute time of the program when the program is finished.

**Comment by danielpinto8zz6** [comment]
can you provide an example?

**Comment by danielpinto8zz6** [comment]
Just add `-ftime-report` flag.
https://stackoverflow.com/questions/3025443/how-to-calculate-gcc-compilation-time/5987523#5987523
