### ISSUE TITLE
create .exe no longer compiles

### ISSUE THREAD

**Issue by Jhonatan-Holanda** [danielpinto8zz6/c-cpp-compile-run#64]
When I press f6 to run the project, only the .exe file is created, but it does not start in the visual code terminal, but in the external terminal it runs without problems, but I wanted to use the own visual code terminal. The problem is that the command to start .exe is like this, for example, "index.exe" and not. \ Index.exe.

![Captura de Tela (51)](https://user-images.githubusercontent.com/32880325/64057195-5dae7200-cb70-11e9-90cf-452fdee38460.png)

as you can see in the image, only what is in "" is returned.

Note: I've seen other bug topics with the same bug, so far no solution of the same

Version VSCODE : 1.37.1
OS: Windows_NT x64 10.0.18362

**Comment by C2dan88** [comment]
On Windows 10 VSCode defaults to powershell as the terminal. When this extension runs the compiled .exe it wraps it in double quotes. To execute a command on double quotes on powershell it needs to be appended with &
Line 58 of VSCodeUI.js (located in C:\Users\<user>\.vscode\extensions\danielpinto8zz6.c-cpp-compile-run-0.5.0\out) needs to be changed to
`                    this.runInTerminal(`& "${executable} ${args}"`, options);`
