### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by znfmxmrhlepf** [danielpinto8zz6/c-cpp-compile-run#66]
- Issue Type: `Performance`
- Extension Name: `c-cpp-compile-run`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\choim\danielpinto8zz6.c-cpp-compile-run-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by danielpinto8zz6** [comment]
Isn't that because of gcc?
