### ISSUE TITLE
When select `Run in external terminal` can not run

### ISSUE THREAD

**Issue by Wangs121** [danielpinto8zz6/c-cpp-compile-run#67]
Thanks for fixing run in VSCode bug, but new bug appears. Sorry to tell u this issue.
![image](https://user-images.githubusercontent.com/15218061/66408684-f8c52200-ea21-11e9-98fc-6acf1bf4acc1.png)

**Comment by danielpinto8zz6** [comment]
I'll fix it soon as possible, thx
