### ISSUE TITLE
Can't compile c source code

### ISSUE THREAD

**Issue by nogamenolifeth** [danielpinto8zz6/c-cpp-compile-run#70]
**Describe the bug**
If I key "F6" down. Vscode will display ",,'C:\Program' is not recognized as an internal or external command,operable program or batch file. visual code"

**Screenshots**
![ภาพ](https://user-images.githubusercontent.com/12609471/66492834-3c319600-eadf-11e9-9e14-fd8de710dc78.png)

**Environment**
 - VSCode Version: 1.38.1
 - OS Version: Windows 10 pro 1903
 - Mingw: x86_64-8.1.0-win32-seh-rt_v6-rev0
 - Extenseion version: 1.0.2 (not have this problem on 0.5.0)

**Comment by danielpinto8zz6** [comment]
Hi, can you test this release and check if problem persists? https://file.io/SeUAim
Thanks

**Comment by nogamenolifeth** [comment]
Return 404 from url

**Comment by danielpinto8zz6** [comment]
https://send.firefox.com/download/72eb097a83f24e12/#sYrg6MCS01tO8Qne1g7_Rw

**Comment by nogamenolifeth** [comment]
> 
> 
> https://send.firefox.com/download/72eb097a83f24e12/#sYrg6MCS01tO8Qne1g7_Rw

It's work. Thanks

**Comment by danielpinto8zz6** [comment]
Nice, I'll make a new release with the fix
