### ISSUE TITLE
Can't compile file with spaces in the filename

### ISSUE THREAD

**Issue by BlahDuckling747** [danielpinto8zz6/c-cpp-compile-run#71]
As the title goes, when a file's name has one or more spaces, the plugin doesn't work.
There used to be quotes around the filename but now it's gone.

how error occurs:
1. open "foo bar.cpp"
2. push F6
4. see error in vscode output:

[foo bar.cpp 2019-10-14 14:20:21.706]
,,g++: error: foo: No such file or directory
g++: error: bar.cpp: No such file or directory
g++: error: bar.exe: No such file or directory
g++: fatal error: no input files
compilation terminated.

ps1: i'm not a native english speaker so sorry for my poor english
ps2: it seems that using 0.5.0 solves it

**Comment by danielpinto8zz6** [comment]
hi, 
update to v1.0.4 and check if it is ok

**Comment by stevenling** [comment]
hello, how can I debug this cpp file，I know F6 is run

**Comment by BlahDuckling747** [comment]
really sorry for not replying
compiling goes well but running still have the same error: no quotes around the filename

**Comment by danielpinto8zz6** [comment]
@BlahDuckling747 are you using external terminal?

**Comment by BlahDuckling747** [comment]
Thank you. It did solved the problem.😀
